### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Pocke01** [Leoneq/iNapMalinka#7]
Hi, 
 
Have a question.  The pcb i got when order from the files in the repo has r10, c12,c18, c10 but the picture of your finished board does not have those.  Is it only to ignore them ? They are on the sides of C11

And the place where you say "DO NOT solder L1-L4, or C3-C6, but instead short them as shown:" 
c3-c6 is left as is? no solder at all?

**Comment by Leoneq** [comment]
Hi! 
Yes, the pictured board is a prototype version, good eye. I was creating instructions along when soldering the prototype, and the sound turned out to be of poor quality till those passives were added.
You need to solder them as the schematic shows, I will update the wiki soon.

As for L1-L4 and C3-C6 I agree it's a wrong sentence, I'll change that too - but as shown, short L1-L4 unless you still get a poor quality sound, and C3-C6 should be left free (just as the picture shows)

**Comment by Pocke01** [comment]
What passives goes on  r10, c12,c18, c10 ?

And is it possible to run without battery only usb-c power?  Cause we havent recieved the battery yet. But my son has finished almost all the soldering.

**Comment by Leoneq** [comment]
As seen here: https://github.com/Leoneq/iNapMalinka/blob/main/pcb/Schematic_iNap%20Malinka_2022-08-17.pdf
In the audio section you can see what values those are. To run without battery you will need to short the `VBAT` with `VUSB`; follow the schematic to see what would be the best place to put the jumper on. Everything should work fine except the overlay, which may show something like "200%" battery charge.

**Comment by Pocke01** [comment]
Thanks for the help!
